Support for Puma 6.0
yabeda-rb/yabeda-puma-plugin pull request #25
Opened 2022-10-17 08:43 UTC by ollym

Puma 6 introduced some small breaking changes to the Puma::Server API, seemed easier to handle these without pattern matching the puma version string.

2022-10-17 16:03 UTC, ollym commented
Hey @Envek let me know if this works or if you'd like a different direction

2022-10-18 04:10 UTC, Envek requested changes
Hey, thanks for the pull request!

In general it should work, yes. However, I wonder, whether it worth the effort to support all Puma version at once. We can just stick with Puma 6 only, I think. Users of older Puma versions always can use older yabeda-puma-plugin versions.

2022-10-18 04:10 UTC, Envek commented on lib/puma/plugin/yabeda_prometheus.rb
> +      metrics = Puma::Server.new app, events, min_threads: 0, max_threads: 1
Puma upgrading notes says:

> If you are creating your own Puma::Server objects, it's initialize signature has changed. In 5.x and below, it was `def initialize(app, events=Events.stdio, options={})`. Now it is `def initialize(app, log_writer=LogWriter.stdio, events=Events.new, options = {})`.

So, initialization should be changed somehow…

2022-10-18 13:54 UTC, ollym commented on lib/puma/plugin/yabeda_prometheus.rb
> +      metrics = Puma::Server.new app, events, min_threads: 0, max_threads: 1
@Envek yea the upgrade notes say that but its not actually how it is in the 6.0 code:
https://github.com/puma/puma/blob/master/lib/puma/server.rb#L74

log_writer is in the options object, not sure if they just got the changelog wrong?

2022-10-18 13:54 UTC, ollym commented
@Envek I'll update the code to only work for Puma 6

2022-10-19 10:12 UTC, Envek commented on lib/puma/plugin/yabeda_prometheus.rb
> +      metrics = Puma::Server.new app, events, min_threads: 0, max_threads: 1
Oh, I see, this change was actually reverted in https://github.com/puma/puma/pull/2965, they just forgot to remove entry from upgrading notes.

2022-10-19 13:19 UTC, Envek commented
Hm, no idea what is wrong with specs…

Most probably some dependencies broke tests, because even current master started to fail with that `Errno::EAGAIN: Resource temporarily unavailable` error…

2022-10-21 10:18 UTC, Envek approved these changes

2022-10-21 10:19 UTC, Envek commented
@skryukov, thanks a lot!

2022-10-21 12:00 UTC, merged

2022-10-21 12:27 UTC, ollym commented
@Envek thanks for merging, think we could get a new gem cut too? Thanks

2022-10-24 10:50 UTC, Envek commented
Thank you for the pull request! Released in [0.7.0](https://github.com/yabeda-rb/yabeda-puma-plugin/releases/tag/v0.7.0)